name: Extract ZIP

on:
  push:
    branches:
      - main

jobs:
  extract-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract ZIP
        run: |
          unzip -q RTX-MUSIX-BOT-v33.zip -d extracted
